# Generated by Django 6.0 on 2025-12-09 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RRHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='ЖД хаб')),
            ],
        ),
        migrations.CreateModel(
            name='StartCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Shanghai', 'Shanghai'), ('Ningbo', 'Ningbo'), ('Tianjin', 'Tianjin'), ('Dalian', 'Dalian'), ('Qingdao', 'Qingdao'), ('Rizhao', 'Rizhao'), ('Xiamen', 'Xiamen'), ('Nansha', 'Nansha'), ('Guangzhou', 'Guangzhou'), ('Yantian', 'Yantian'), ('Shekou', 'Shekou'), ('Lianyungang', 'Lianyungang'), ('Hongkong', 'Hongkong'), ('Taicang', 'Taicang')], max_length=32, unique=True, verbose_name='Город отправки')),
            ],
        ),
        migrations.CreateModel(
            name='EndCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Город доставки')),
                ('rr_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_cities', to='paths.rrhub')),
            ],
        ),
        migrations.CreateModel(
            name='RRStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='ЖД станция')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('rr_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_stations', to='paths.rrhub')),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.endcity')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.startcity')),
            ],
        ),
    ]
