# Generated by Django 6.0 on 2025-12-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Порт')),
            ],
        ),
        migrations.CreateModel(
            name='RRHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='ЖД хаб')),
            ],
        ),
        migrations.CreateModel(
            name='StartPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Shanghai', 'Shanghai'), ('Ningbo', 'Ningbo'), ('Tianjin', 'Tianjin'), ('Dalian', 'Dalian'), ('Qingdao', 'Qingdao'), ('Rizhao', 'Rizhao'), ('Xiamen', 'Xiamen'), ('Nansha', 'Nansha'), ('Guangzhou', 'Guangzhou'), ('Yantian', 'Yantian'), ('Shekou', 'Shekou'), ('Lianyungang', 'Lianyungang'), ('Hongkong', 'Hongkong'), ('Taicang', 'Taicang')], max_length=32, unique=True, verbose_name='Порт отправки')),
            ],
        ),
        migrations.CreateModel(
            name='EndPortSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Сателлит порта')),
                ('end_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellites', to='paths.endport')),
            ],
        ),
        migrations.CreateModel(
            name='InlandEndCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Город удаленный от порта')),
                ('rr_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inland_cities', to='paths.rrhub')),
            ],
        ),
        migrations.CreateModel(
            name='RRStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='ЖД станция')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('rr_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_stations', to='paths.rrhub')),
            ],
        ),
        migrations.CreateModel(
            name='SeaLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Морская линия')),
                ('end_ports', models.ManyToManyField(related_name='sea_lines', to='paths.endport')),
                ('start_ports', models.ManyToManyField(related_name='sea_lines', to='paths.startport')),
            ],
        ),
        migrations.CreateModel(
            name='SeaRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('end_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_rates', to='paths.endport')),
                ('sea_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_rates', to='paths.sealine')),
                ('start_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_rates', to='paths.startport')),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(max_length=32, verbose_name='Город доставки')),
                ('cheapest', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Самый дешевый')),
                ('start_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.startport')),
            ],
        ),
    ]
