# Generated by Django 6.0 on 2026-02-15 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalHubCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Портовый город прибытия')),
            ],
            options={
                'verbose_name': 'Портовый город прибытия',
                'verbose_name_plural': 'Портовые города прибытия',
            },
        ),
        migrations.CreateModel(
            name='RREndCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Город ЖД прибытия')),
            ],
            options={
                'verbose_name': 'Город ЖД прибытия',
                'verbose_name_plural': 'Города ЖД прибытия',
            },
        ),
        migrations.CreateModel(
            name='RRETD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etd', models.DateField(verbose_name='Дата выхода ЖД')),
            ],
            options={
                'verbose_name': 'Дата выхода ЖД',
                'verbose_name_plural': 'Даты выхода ЖД',
                'ordering': ['etd'],
            },
        ),
        migrations.CreateModel(
            name='RRStartCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Город ЖД отправки')),
            ],
            options={
                'verbose_name': 'Город ЖД отправки',
                'verbose_name_plural': 'Города ЖД отправки',
            },
        ),
        migrations.CreateModel(
            name='SeaETD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etd', models.DateField(verbose_name='Дата выхода судна')),
            ],
            options={
                'verbose_name': 'Дата выхода судна',
                'verbose_name_plural': 'Даты выхода судов',
                'ordering': ['etd'],
            },
        ),
        migrations.CreateModel(
            name='SeaLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Морская линия')),
            ],
            options={
                'verbose_name': 'Морская линия',
                'verbose_name_plural': 'Морские линии',
            },
        ),
        migrations.CreateModel(
            name='StartPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Shanghai', 'Shanghai'), ('Ningbo', 'Ningbo'), ('Tianjin', 'Tianjin'), ('Dalian', 'Dalian'), ('Qingdao', 'Qingdao'), ('Rizhao', 'Rizhao'), ('Xiamen', 'Xiamen'), ('Nansha', 'Nansha'), ('Guangzhou', 'Guangzhou'), ('Yantian', 'Yantian'), ('Shekou', 'Shekou'), ('Lianyungang', 'Lianyungang'), ('Hongkong', 'Hongkong'), ('Taicang', 'Taicang')], max_length=32, unique=True, verbose_name='Порт отправки')),
            ],
            options={
                'verbose_name': 'Порт отправки',
                'verbose_name_plural': 'Порты отправки',
            },
        ),
        migrations.CreateModel(
            name='TruckEndCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Город автодовоза')),
            ],
            options={
                'verbose_name': 'Город автодовоза',
                'verbose_name_plural': 'Города автодовоза',
            },
        ),
        migrations.CreateModel(
            name='RREndTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='ЖД терминал прибытия')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_terminals', to='paths.rrendcity', verbose_name='Город ЖД прибытия')),
            ],
            options={
                'verbose_name': 'ЖД терминал прибытия',
                'verbose_name_plural': 'ЖД терминалы прибытия',
            },
        ),
        migrations.CreateModel(
            name='RRRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity', models.DateField(verbose_name='Валидность до')),
                ('container', models.CharField(choices=[('20DC', '20DC'), ('H0HC', '40HC')], max_length=16, verbose_name='Тип КТК')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('end_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='paths.rrendterminal')),
                ('etd', models.ManyToManyField(related_name='rates', to='paths.rretd')),
            ],
            options={
                'verbose_name': 'ЖД ставка',
                'verbose_name_plural': 'ЖД ставки',
            },
        ),
        migrations.CreateModel(
            name='RRCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etd_from', models.DateField(blank=True, null=True, verbose_name='Выход от')),
                ('etd_to', models.DateField(blank=True, null=True, verbose_name='Выход до')),
                ('container', models.CharField(choices=[('20DC', '20DC'), ('H0HC', '40HC')], max_length=16, verbose_name='Тип КТК')),
                ('end_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_calculations', to='paths.rrendcity')),
                ('cheapest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheapest_calculations', to='paths.rrrate')),
                ('fastest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastest_calculations', to='paths.rrrate')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_calculations', to='paths.rrstartcity')),
            ],
            options={
                'verbose_name': 'Расчёт прямого ЖД',
                'verbose_name_plural': 'Расчёты прямого ЖД',
            },
        ),
        migrations.CreateModel(
            name='RRStartTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='ЖД терминал отправки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_terminals', to='paths.rrstartcity', verbose_name='Город ЖД отправки')),
            ],
            options={
                'verbose_name': 'ЖД терминал отправки',
                'verbose_name_plural': 'ЖД терминалы отправки',
            },
        ),
        migrations.AddField(
            model_name='rrrate',
            name='start_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='paths.rrstartterminal'),
        ),
        migrations.CreateModel(
            name='InnerRRRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(choices=[('20DC', '20DC'), ('H0HC', '40HC')], max_length=16, verbose_name='Тип КТК')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('end_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_rates', to='paths.rrendterminal')),
                ('start_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_rates', to='paths.rrstartterminal')),
            ],
            options={
                'verbose_name': 'Внутренняя ЖД ставка',
                'verbose_name_plural': 'Внутренние ЖД ставки',
            },
        ),
        migrations.CreateModel(
            name='SeaEndTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Морской терминал прибытия')),
                ('local_hub_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_terminals', to='paths.localhubcity')),
            ],
            options={
                'verbose_name': 'Морской терминал прибытия',
                'verbose_name_plural': 'Морские терминалы прибытия',
            },
        ),
        migrations.CreateModel(
            name='SeaRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity', models.DateField(verbose_name='Валидность до')),
                ('container', models.CharField(choices=[('20DC', '20DC'), ('H0HC', '40HC')], max_length=16, verbose_name='Тип КТК')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('etd', models.ManyToManyField(related_name='sea_rates', to='paths.seaetd')),
                ('sea_end_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_rates', to='paths.seaendterminal')),
                ('sea_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_rates', to='paths.sealine')),
                ('start_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_rates', to='paths.startport')),
            ],
            options={
                'verbose_name': 'Морская ставка',
                'verbose_name_plural': 'Морские ставки',
            },
        ),
        migrations.CreateModel(
            name='SeaCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etd_from', models.DateField(blank=True, null=True, verbose_name='Выход от')),
                ('etd_to', models.DateField(blank=True, null=True, verbose_name='Выход до')),
                ('container', models.CharField(choices=[('20DC', '20DC'), ('H0HC', '40HC')], max_length=16, verbose_name='Тип КТК')),
                ('sea_end_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_calculations', to='paths.seaendterminal', verbose_name='Терминал прибытия')),
                ('cheapest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheapest_calculations', to='paths.searate')),
                ('fastest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastest_calculations', to='paths.searate')),
                ('start_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_calculations', to='paths.startport', verbose_name='Порт отправки')),
            ],
            options={
                'verbose_name': 'Расчёт моря',
                'verbose_name_plural': 'Расчёты моря',
            },
        ),
        migrations.CreateModel(
            name='SeaRRCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etd_from', models.DateField(blank=True, null=True, verbose_name='Выход от')),
                ('etd_to', models.DateField(blank=True, null=True, verbose_name='Выход до')),
                ('container', models.CharField(choices=[('20DC', '20DC'), ('H0HC', '40HC')], max_length=16, verbose_name='Тип КТК')),
                ('gross', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Брутто')),
                ('is_VTT', models.BooleanField(default=False, verbose_name='ВТТ')),
                ('rr_end_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.rrendterminal')),
                ('sea_end_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.seaendterminal')),
                ('start_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.startport')),
                ('truck_end_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.truckendcity')),
            ],
        ),
    ]
