# Generated by Django 6.0 on 2026-02-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckEndCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Город автодовоза')),
            ],
            options={
                'verbose_name': 'Город автодовоза',
                'verbose_name_plural': 'Города автодовоза',
            },
        ),
        migrations.CreateModel(
            name='SeaRRCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etd_from', models.DateField(blank=True, null=True, verbose_name='Выход от')),
                ('etd_to', models.DateField(blank=True, null=True, verbose_name='Выход до')),
                ('container', models.CharField(choices=[('20DC', '20DC'), ('H0HC', '40HC')], max_length=16, verbose_name='Тип КТК')),
                ('gross', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Брутто')),
                ('is_VTT', models.BooleanField(default=False, verbose_name='ВТТ')),
                ('rr_end_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.rrendterminal')),
                ('sea_end_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.seaendterminal')),
                ('start_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.startport')),
                ('truck_end_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.truckendcity')),
            ],
        ),
    ]
