# Generated by Django 6.0 on 2025-12-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searate',
            name='etd',
        ),
        migrations.AddField(
            model_name='searate',
            name='etd',
            field=models.ManyToManyField(related_name='sea_etds', to='paths.seaetd'),
        ),
    ]
