# Generated by Django 6.0 on 2026-02-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RRStartCity',
            new_name='ForeignRRStartCity',
        ),
    ]
