# Generated by Django 6.0 on 2026-02-22 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searrcalculation',
            name='end_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.localhubcity'),
        ),
        migrations.RemoveField(
            model_name='trucktoendcityrate',
            name='end_cities',
        ),
        migrations.RemoveField(
            model_name='trucktoendcityrate',
            name='local_hub_cities',
        ),
        migrations.DeleteModel(
            name='EndCity',
        ),
        migrations.DeleteModel(
            name='TruckToEndCityRate',
        ),
    ]
