# Generated by Django 6.0 on 2026-03-23 12:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerrrrate',
            name='pol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_rr_rates', to='paths.seastartterminal'),
        ),
        migrations.AlterField(
            model_name='innerrrrate',
            name='container',
            field=models.CharField(choices=[('20DC', '20DC'), ('40HC', '40HC')], max_length=16, verbose_name='Тип КТК'),
        ),
        migrations.AlterField(
            model_name='rrcalculation',
            name='container',
            field=models.CharField(choices=[('20DC', '20DC'), ('40HC', '40HC')], max_length=16, verbose_name='Тип КТК'),
        ),
        migrations.AlterField(
            model_name='rrrate',
            name='container',
            field=models.CharField(choices=[('20DC', '20DC'), ('40HC', '40HC')], max_length=16, verbose_name='Тип КТК'),
        ),
        migrations.AlterField(
            model_name='seacalculation',
            name='container',
            field=models.CharField(choices=[('20DC', '20DC'), ('40HC', '40HC')], max_length=16, verbose_name='Тип КТК'),
        ),
        migrations.AlterField(
            model_name='searate',
            name='container',
            field=models.CharField(choices=[('20DC', '20DC'), ('40HC', '40HC')], max_length=16, verbose_name='Тип КТК'),
        ),
        migrations.AlterField(
            model_name='searrcalculation',
            name='container',
            field=models.CharField(choices=[('20DC', '20DC'), ('40HC', '40HC')], max_length=16, verbose_name='Тип КТК'),
        ),
        migrations.AlterField(
            model_name='searrcalculation',
            name='gross',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MaxValueValidator(28000)], verbose_name='Брутто'),
        ),
    ]
