# Generated by Django 6.0 on 2026-02-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeaRRRate',
        ),
    ]
