# Generated by Django 6.0 on 2026-03-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searate',
            name='rate_20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Стоимость за 20ft, $'),
        ),
        migrations.AlterField(
            model_name='searate',
            name='rate_40',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Стоимость за 40ft, $'),
        ),
    ]
