# Generated by Django 6.0 on 2025-12-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seacalculation',
            name='eta',
        ),
        migrations.RemoveField(
            model_name='searate',
            name='eta',
        ),
    ]
