# Generated by Django 6.0 on 2026-02-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartPortCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Shanghai', 'Shanghai'), ('Ningbo', 'Ningbo'), ('Tianjin', 'Tianjin'), ('Dalian', 'Dalian'), ('Qingdao', 'Qingdao'), ('Rizhao', 'Rizhao'), ('Xiamen', 'Xiamen'), ('Nansha', 'Nansha'), ('Guangzhou', 'Guangzhou'), ('Yantian', 'Yantian'), ('Shekou', 'Shekou'), ('Lianyungang', 'Lianyungang'), ('Hongkong', 'Hongkong'), ('Taicang', 'Taicang')], max_length=32, unique=True, verbose_name='Город отправки судна')),
            ],
            options={
                'verbose_name': 'Город отправки судна',
                'verbose_name_plural': 'Города отправки судна',
            },
        ),
    ]
