# Generated by Django 6.0 on 2026-03-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerrrrate',
            name='is_by_wagon',
            field=models.BooleanField(default=False, verbose_name='Повагонная отправка'),
        ),
    ]
