# Generated by Django 6.0 on 2026-02-16 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_rename_rrstartcity_foreignrrstartcity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foreignrrstartcity',
            options={'verbose_name': 'Зарубежный город ЖД отправки', 'verbose_name_plural': 'Зарубежные города ЖД отправки'},
        ),
        migrations.AlterField(
            model_name='foreignrrstartcity',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Зарубежный город ЖД отправки'),
        ),
        migrations.CreateModel(
            name='ForeignRRStartTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Зарубежный ЖД терминал отправки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_terminals', to='paths.foreignrrstartcity', verbose_name='Город ЖД отправки')),
            ],
            options={
                'verbose_name': 'ЖД терминал отправки',
                'verbose_name_plural': 'ЖД терминалы отправки',
            },
        ),
        migrations.AlterField(
            model_name='rrrate',
            name='start_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='paths.foreignrrstartterminal'),
        ),
        migrations.CreateModel(
            name='InnerRRStartTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Зарубежный ЖД терминал отправки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_terminals', to='paths.localhubcity', verbose_name='Город ЖД отправки')),
            ],
            options={
                'verbose_name': 'Внутренний ЖД терминал отправки',
                'verbose_name_plural': 'Внутренние ЖД терминалы отправки',
            },
        ),
        migrations.AlterField(
            model_name='innerrrrate',
            name='start_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_rates', to='paths.innerrrstartterminal'),
        ),
        migrations.DeleteModel(
            name='RRStartTerminal',
        ),
    ]
