# Generated by Django 6.0 on 2026-02-22 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_delete_searrrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distanttruckrate',
            name='end_cities',
        ),
        migrations.RemoveField(
            model_name='distanttruckrate',
            name='start_cities',
        ),
        migrations.AddField(
            model_name='distanttruckrate',
            name='end_city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ingoing_truck_rates', to='paths.localhubcity', verbose_name='Город прибытия автовывоза'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distanttruckrate',
            name='start_city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_truck_rates', to='paths.localhubcity', verbose_name='Город отправки автовывоза'),
            preserve_default=False,
        ),
    ]
