# Generated by Django 6.0 on 2026-03-25 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_innerrrrate_pol_alter_innerrrrate_container_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searate',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='paths.foreignagent', verbose_name='Агент'),
        ),
    ]
