# Generated by Django 6.0 on 2026-03-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_innerrrrate_is_by_wagon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innerrrterminal',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Внутренний ЖД терминал'),
        ),
    ]
