# Generated by Django 6.0 on 2025-12-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_calculation_rr_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='rr_cost',
            new_name='terminal_cost',
        ),
    ]
