# Generated by Django 6.0 on 2025-12-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_remove_searate_etd_searate_etd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seaetd',
            options={'ordering': ['etd']},
        ),
        migrations.AlterField(
            model_name='searate',
            name='etd',
            field=models.ManyToManyField(related_name='sea_rates', to='paths.seaetd'),
        ),
    ]
