# Generated by Django 6.0 on 2026-02-15 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_startportcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='startport',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='paths.startportcity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startportcity',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Город отправки судна'),
        ),
    ]
