# Generated by Django 6.0 on 2025-12-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_alter_startcity_start_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startcity',
            old_name='start_city',
            new_name='name',
        ),
    ]
