# Generated by Django 6.0 on 2025-12-13 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_remove_seacalculation_eta_remove_searate_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='seacalculation',
            name='fastest',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fastest_calculations', to='paths.searate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seacalculation',
            name='cheapest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheapest_calculations', to='paths.searate'),
        ),
        migrations.AlterField(
            model_name='seacalculation',
            name='sea_end_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_calculations', to='paths.seaendterminal'),
        ),
        migrations.AlterField(
            model_name='seacalculation',
            name='start_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_calculations', to='paths.startport'),
        ),
    ]
