# Generated by Django 6.0 on 2026-02-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_fileupload_alter_searate_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='searate',
            name='intermediate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_point_rates', to='paths.seastartterminal'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_file',
            field=models.FileField(upload_to='uploads/', verbose_name='Файл со ставками'),
        ),
    ]
