# Generated by Django 6.0 on 2026-03-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_alter_searate_rate_20_alter_searate_rate_40'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerrrrate',
            name='rate_20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Стоимость за 20ft, $'),
        ),
        migrations.AddField(
            model_name='innerrrrate',
            name='rate_40',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Стоимость за 40ft, $'),
        ),
    ]
