# Generated by Django 6.0 on 2026-03-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_innerrrrate_rate_20_innerrrrate_rate_40'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searate',
            name='sea_end_terminal',
        ),
        migrations.AddField(
            model_name='searate',
            name='sea_end_terminal',
            field=models.ManyToManyField(related_name='sea_rates', to='paths.seaendterminal'),
        ),
    ]
