# Generated by Django 6.0 on 2026-03-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_alter_searate_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerrrterminal',
            name='gtd_20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Прием 20фт ГТД'),
        ),
        migrations.AddField(
            model_name='innerrrterminal',
            name='gtd_40',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Прием 40фт ГТД'),
        ),
        migrations.AddField(
            model_name='innerrrterminal',
            name='vtt_20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Прием 20фт ВТТ'),
        ),
        migrations.AddField(
            model_name='innerrrterminal',
            name='vtt_40',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Прием 40фт ВТТ'),
        ),
    ]
