# Generated by Django 6.0 on 2025-12-13 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_seacalculation_fastest_alter_seacalculation_cheapest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seacalculation',
            name='cheapest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheapest_calculations', to='paths.searate'),
        ),
        migrations.AlterField(
            model_name='seacalculation',
            name='fastest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastest_calculations', to='paths.searate'),
        ),
    ]
