# Generated by Django 6.0 on 2026-03-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_alter_innerrrterminal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innerrrrate',
            name='rate_20',
        ),
        migrations.AddField(
            model_name='innerrrrate',
            name='rate_20_24',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Стоимость за 20ft до 24т, $'),
        ),
        migrations.AddField(
            model_name='innerrrrate',
            name='rate_20_28',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Стоимость за 20ft 24-28т, $'),
        ),
        migrations.AddField(
            model_name='innerrrrate',
            name='thc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Терминальные расходы'),
            preserve_default=False,
        ),
    ]
