# Generated by Django 6.0 on 2025-12-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_rename_rr_cost_calculation_terminal_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='RussianPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Российский порт')),
            ],
        ),
        migrations.RenameModel(
            old_name='StartCity',
            new_name='ForeignPort',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='start_city',
            new_name='foreign_port',
        ),
        migrations.CreateModel(
            name='SeaLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Морская линия')),
                ('russian_ports', models.ManyToManyField(related_name='sealines', to='paths.russianport')),
            ],
        ),
    ]
