# Generated by Django 6.0 on 2026-02-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_searate_intermediate_alter_fileupload_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Агент')),
            ],
        ),
        migrations.AddField(
            model_name='searate',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='paths.foreignagent'),
        ),
    ]
