# Generated by Django 6.0 on 2026-02-16 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_alter_foreignrrstartcity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rrendterminal',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_terminals', to='paths.localhubcity', verbose_name='Город ЖД прибытия'),
        ),
        migrations.AlterField(
            model_name='rrcalculation',
            name='end_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_calculations', to='paths.localhubcity'),
        ),
        migrations.DeleteModel(
            name='RREndCity',
        ),
    ]
