# Generated by Django 6.0 on 2025-12-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0004_russianport_rename_startcity_foreignport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sealine',
            name='foreign_ports',
            field=models.ManyToManyField(related_name='sealines', to='paths.foreignport'),
        ),
    ]
