# Generated by Django 6.0 on 2026-03-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0004_innerrrterminal_gtd_20_innerrrterminal_gtd_40_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innerrrterminal',
            name='gtd_20',
        ),
        migrations.RemoveField(
            model_name='innerrrterminal',
            name='gtd_40',
        ),
        migrations.RemoveField(
            model_name='innerrrterminal',
            name='vtt_20',
        ),
        migrations.RemoveField(
            model_name='innerrrterminal',
            name='vtt_40',
        ),
    ]
