# Generated by Django 6.0 on 2026-02-16 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0004_alter_rrendterminal_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localhubcity',
            options={'verbose_name': 'Внутренний транспортный хаб', 'verbose_name_plural': 'Внутренние транспортные хабы'},
        ),
        migrations.AlterModelOptions(
            name='rrrate',
            options={'verbose_name': 'Прямая ЖД ставка', 'verbose_name_plural': 'Прямые ЖД ставки'},
        ),
        migrations.AddField(
            model_name='endcity',
            name='local_hub_city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='end_cities', to='paths.localhubcity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='innerrrstartterminal',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Внутренний ЖД терминал отправки'),
        ),
        migrations.AlterField(
            model_name='localhubcity',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Внутренний транспортный хаб'),
        ),
    ]
