# Generated by Django 6.0 on 2026-03-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0004_remove_searate_sea_end_terminal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searate',
            name='rate',
        ),
    ]
