# Generated by Django 6.0 on 2025-12-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0004_alter_seacalculation_cheapest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seacalculation',
            name='container',
            field=models.CharField(choices=[('20DC', '20DC'), ('H0HC', '40HC')], default='20DC', max_length=16, verbose_name='Тип КТК'),
            preserve_default=False,
        ),
    ]
