# Generated by Django 6.0 on 2026-03-01 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0004_foreignagent_searate_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foreignagent',
            options={'verbose_name': 'Агент', 'verbose_name_plural': 'Агенты'},
        ),
        migrations.AddField(
            model_name='innerrrrate',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inner_rr_rates', to='paths.sealine'),
            preserve_default=False,
        ),
    ]
