# Generated by Django 6.0 on 2026-02-17 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0005_alter_localhubcity_options_alter_rrrate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endcity',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Стоимость автовывоза'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SeaRRRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rr_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sea_rr_rates', to='paths.rrrate')),
                ('sea_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_rr_rates', to='paths.searate')),
            ],
        ),
    ]
