# Generated by Django 6.0 on 2025-12-13 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0005_seacalculation_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='searate',
            name='container',
            field=models.CharField(choices=[('20DC', '20DC'), ('H0HC', '40HC')], default='20DC', max_length=16, verbose_name='Тип КТК'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seacalculation',
            name='sea_end_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_calculations', to='paths.seaendterminal', verbose_name='Терминал прибытия'),
        ),
        migrations.AlterField(
            model_name='seacalculation',
            name='start_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_calculations', to='paths.startport', verbose_name='Порт отправки'),
        ),
    ]
