# Generated by Django 6.0 on 2026-03-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0005_remove_innerrrterminal_gtd_20_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerrrterminal',
            name='gtd_20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='innerrrterminal',
            name='gtd_40',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='innerrrterminal',
            name='vtt_20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='innerrrterminal',
            name='vtt_40',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
