# Generated by Django 6.0 on 2026-03-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0005_alter_foreignagent_options_innerrrrate_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innerrrrate',
            name='end_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_rates_incoming', to='paths.innerrrterminal', verbose_name='ЖД терминал прибытия'),
        ),
        migrations.AlterField(
            model_name='innerrrrate',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_rr_rates', to='paths.sealine', verbose_name='Линия'),
        ),
        migrations.AlterField(
            model_name='innerrrrate',
            name='start_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_rates_outgoing', to='paths.innerrrterminal', verbose_name='ЖД терминал отправки'),
        ),
    ]
