# Generated by Django 6.0 on 2025-12-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0005_sealine_foreign_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sealine',
            name='foreign_ports',
            field=models.ManyToManyField(related_name='sea_lines', to='paths.foreignport'),
        ),
        migrations.AlterField(
            model_name='sealine',
            name='russian_ports',
            field=models.ManyToManyField(related_name='sea_lines', to='paths.russianport'),
        ),
        migrations.CreateModel(
            name='SeaRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_rates', to='paths.foreignport')),
                ('russian_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_rates', to='paths.russianport')),
                ('sea_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_rates', to='paths.sealine')),
            ],
        ),
    ]
