# Generated by Django 6.0 on 2026-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0006_alter_innerrrrate_end_terminal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searate',
            name='etd',
            field=models.ManyToManyField(blank=True, related_name='sea_rates', to='paths.seaetd'),
        ),
    ]
