# Generated by Django 6.0 on 2026-03-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0006_innerrrterminal_gtd_20_innerrrterminal_gtd_40_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerrrterminal',
            name='local_truck',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
