# Generated by Django 6.0 on 2026-02-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0006_endcity_rate_searrrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searrrate',
            name='rr_rate',
        ),
        migrations.AddField(
            model_name='searrrate',
            name='inner_rr_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sea_rr_rates', to='paths.innerrrrate'),
        ),
    ]
