# Generated by Django 6.0 on 2025-12-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0006_alter_sealine_foreign_ports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
