# Generated by Django 6.0 on 2025-12-09 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0007_searate_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sealine',
            name='russian_ports',
        ),
        migrations.AlterField(
            model_name='searate',
            name='russian_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_rates', to='paths.endcity'),
        ),
        migrations.AddField(
            model_name='endcity',
            name='logistic_status',
            field=models.CharField(choices=[('Порт', 'is a port'), ('Автодоставка из порта', 'truck after port'), ('ЖД доставка из порта', 'RW after port')], default='Порт', max_length=32, verbose_name='Логистический статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sealine',
            name='end_cities',
            field=models.ManyToManyField(related_name='sea_lines', to='paths.endcity'),
        ),
        migrations.AlterField(
            model_name='foreignport',
            name='name',
            field=models.CharField(choices=[('Shanghai', 'Shanghai'), ('Ningbo', 'Ningbo'), ('Tianjin', 'Tianjin'), ('Dalian', 'Dalian'), ('Qingdao', 'Qingdao'), ('Rizhao', 'Rizhao'), ('Xiamen', 'Xiamen'), ('Nansha', 'Nansha'), ('Guangzhou', 'Guangzhou'), ('Yantian', 'Yantian'), ('Shekou', 'Shekou'), ('Lianyungang', 'Lianyungang'), ('Hongkong', 'Hongkong'), ('Taicang', 'Taicang')], max_length=32, unique=True, verbose_name='Порт отправки'),
        ),
        migrations.DeleteModel(
            name='RussianPort',
        ),
    ]
