# Generated by Django 6.0 on 2026-03-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0007_alter_searate_etd'),
    ]

    operations = [
        migrations.AddField(
            model_name='searate',
            name='conversion',
            field=models.IntegerField(default=3, verbose_name='Конвертация, %'),
            preserve_default=False,
        ),
    ]
