# Generated by Django 6.0 on 2026-02-17 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0007_remove_searrrate_rr_rate_searrrate_inner_rr_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searrrate',
            options={'verbose_name': 'Ставка море + ЖД', 'verbose_name_plural': 'Ставки море + ЖД'},
        ),
        migrations.AddField(
            model_name='localhubcity',
            name='truck_delivery_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_hub_cities', to='paths.endcity'),
        ),
        migrations.AlterField(
            model_name='searrcalculation',
            name='rr_end_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.rrendterminal', verbose_name='ЖД терминал прибытия'),
        ),
        migrations.AlterField(
            model_name='searrcalculation',
            name='sea_start_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='paths.seastartterminal', verbose_name='Морской терминал отправки'),
        ),
    ]
