# Generated by Django 6.0 on 2026-03-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0007_innerrrterminal_local_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innerrrrate',
            name='container',
        ),
    ]
