# Generated by Django 6.0 on 2026-02-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0008_alter_searrrate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endcity',
            name='local_hub_city',
        ),
        migrations.RemoveField(
            model_name='localhubcity',
            name='truck_delivery_point',
        ),
        migrations.AddField(
            model_name='localhubcity',
            name='truck_delivery_point',
            field=models.ManyToManyField(blank=True, null=True, related_name='local_hub_cities', to='paths.endcity'),
        ),
    ]
