# Generated by Django 6.0 on 2025-12-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0008_remove_sealine_russian_ports_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='terminal_cost',
        ),
        migrations.AddField(
            model_name='calculation',
            name='cheapest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Самый дешевый'),
            preserve_default=False,
        ),
    ]
