# Generated by Django 6.0 on 2026-03-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0008_remove_innerrrrate_container'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localhubcity',
            options={'verbose_name': 'Автовывоз внутри города', 'verbose_name_plural': 'Автовывозы внутри городов'},
        ),
        migrations.AddField(
            model_name='localhubcity',
            name='local_truck',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.DeleteModel(
            name='LocalTruck',
        ),
    ]
