# Generated by Django 6.0 on 2026-03-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0008_searate_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searate',
            name='conversion',
            field=models.FloatField(verbose_name='Конвертация, %'),
        ),
    ]
