# Generated by Django 6.0 on 2026-02-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0009_remove_endcity_local_hub_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localhubcity',
            name='local_truck_delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена автовывоза по городу'),
            preserve_default=False,
        ),
    ]
