# Generated by Django 6.0 on 2026-04-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0009_alter_localhubcity_options_localhubcity_local_truck_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localhubcity',
            options={'verbose_name': 'Внутренний транспортный хаб', 'verbose_name_plural': 'Внутренние транспортные хабы'},
        ),
    ]
