# Generated by Django 6.0 on 2026-02-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0010_localhubcity_local_truck_delivery_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckToEndCityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена автовывоза до конечного города')),
                ('end_cities', models.ManyToManyField(related_name='end_city_rates', to='paths.endcity')),
                ('local_hub_cities', models.ManyToManyField(related_name='end_city_rates', to='paths.localhubcity')),
            ],
        ),
    ]
