# Generated by Django 6.0 on 2026-04-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0010_alter_localhubcity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='searate',
            name='drop_off',
            field=models.ManyToManyField(related_name='sea_rate_drop', to='paths.localhubcity', verbose_name='Дроп офф'),
        ),
    ]
