# Generated by Django 6.0 on 2026-04-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0011_searate_drop_off'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localhubcity',
            options={'ordering': ('name',), 'verbose_name': 'Внутренний транспортный хаб', 'verbose_name_plural': 'Внутренние транспортные хабы'},
        ),
        migrations.AlterModelOptions(
            name='seastartterminal',
            options={'ordering': ('name',), 'verbose_name': 'Порт отправки', 'verbose_name_plural': 'Порты отправки'},
        ),
        migrations.AddField(
            model_name='searrcalculation',
            name='with_guard',
            field=models.BooleanField(default=False, verbose_name='С охраной'),
        ),
    ]
