# Generated by Django 6.0 on 2026-02-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0011_trucktoendcityrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена автовывоза по городу')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_truck', to='paths.localhubcity', verbose_name='Город локального автовывоза')),
            ],
        ),
    ]
