# Generated by Django 6.0 on 2026-04-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0012_alter_localhubcity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerrrrate',
            name='guard_20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Охрана 20фт'),
        ),
        migrations.AddField(
            model_name='innerrrrate',
            name='guard_40',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Охрана 40фт'),
        ),
    ]
