# Generated by Django 6.0 on 2026-02-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0012_localtruck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localtruck',
            options={'verbose_name': 'Автовывоз внутри города', 'verbose_name_plural': 'Автовывозы внутри городов'},
        ),
        migrations.RemoveField(
            model_name='localhubcity',
            name='local_truck_delivery_price',
        ),
    ]
