# Generated by Django 6.0 on 2026-02-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0013_alter_localtruck_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistantTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена автовывоза между городами')),
                ('end_city', models.ManyToManyField(related_name='end_cities', to='paths.localhubcity', verbose_name='end_cities')),
                ('start_city', models.ManyToManyField(related_name='start_cities', to='paths.localhubcity', verbose_name='start_cities')),
            ],
            options={
                'verbose_name': 'Автовывоз между городами',
                'verbose_name_plural': 'Автовывозы между городами',
            },
        ),
    ]
