# Generated by Django 6.0 on 2026-04-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0013_innerrrrate_guard_20_innerrrrate_guard_40'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searate',
            name='conversion',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Конвертация, %'),
        ),
    ]
