# Generated by Django 6.0 on 2026-02-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0014_distanttruck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localhubcity',
            name='truck_delivery_point',
        ),
    ]
