# Generated by Django 6.0 on 2026-02-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0015_remove_localhubcity_truck_delivery_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distanttruck',
            old_name='end_city',
            new_name='end_cities',
        ),
        migrations.RenameField(
            model_name='distanttruck',
            old_name='start_city',
            new_name='start_cities',
        ),
    ]
