# Generated by Django 6.0 on 2026-02-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0016_rename_end_city_distanttruck_end_cities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distanttruck',
            name='end_cities',
            field=models.ManyToManyField(related_name='end_cities', to='paths.localhubcity', verbose_name='end_truck_remote'),
        ),
        migrations.AlterField(
            model_name='distanttruck',
            name='start_cities',
            field=models.ManyToManyField(related_name='start_cities', to='paths.localhubcity', verbose_name='start_truck_remote'),
        ),
    ]
