# Generated by Django 6.0 on 2026-02-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0017_alter_distanttruck_end_cities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistantTruckRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена автовывоза между городами')),
                ('end_cities', models.ManyToManyField(related_name='ingoing_truck_rates', to='paths.localhubcity', verbose_name='Города прибытия автовывоза')),
                ('start_cities', models.ManyToManyField(related_name='outgoing_truck_rates', to='paths.localhubcity', verbose_name='Города отправки автовывоза')),
            ],
            options={
                'verbose_name': 'Автовывоз между городами',
                'verbose_name_plural': 'Автовывозы между городами',
            },
        ),
        migrations.DeleteModel(
            name='DistantTruck',
        ),
    ]
